name: Portfolio CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      PORTFOLIO_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and tag image
        run: |
          docker build -t "portfolio" ./
          docker tag "portfolio" "${{ secrets.DOCKER_REPOSITORY }}:${{ env.PORTFOLIO_TAG }}"
      
      - name: Push image to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push "${{ secrets.DOCKER_REPOSITORY }}:${{ env.PORTFOLIO_TAG }}"

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Exporting necessary secrets..."
            export DOCKER_REPOSITORY=${{ secrets.DOCKER_REPOSITORY }}
            export PORTFOLIO_TAG=${{ env.PORTFOLIO_TAG }}
    
            echo "Logging in to Docker Hub..."
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

            echo "Running docker compose..."
            docker compose --env-file ./.env up --build node -d

            echo "Removing unused images..."
            docker image prune -fa